CREATE TABLE cbc_alerta (
id SERIAL PRIMARY KEY,
estado VARCHAR(50) NOT NULL,
operadora VARCHAR(50) NOT NULL,
mme VARCHAR(50),
amf VARCHAR(50),
status VARCHAR(20) NOT NULL,
teste VARCHAR(50),
roteamento VARCHAR(50),
tecnologia VARCHAR(10) GENERATED ALWAYS AS (CASE WHEN amf IS NOT NULL THEN '5G' ELSE 'MME' END) STORED,
CHECK ((mme IS NOT NULL AND amf IS NULL) OR (mme IS NULL AND amf IS NOT NULL))
);